"""empty message

Revision ID: 6b7d3b7d9911
Revises: 
Create Date: 2018-05-30 03:50:24.185181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7d3b7d9911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_routes',
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('cr_id')
    )
    op.create_table('directions',
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('direction_text', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('direction_id')
    )
    op.create_table('interest_points',
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('poi_id')
    )
    op.create_table('path_steps',
    sa.Column('ps_id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('ps_id')
    )
    op.create_table('paths',
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('start_point', sa.Integer(), nullable=False),
    sa.Column('end_point', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('waypoints', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('route_difficulty', sa.String(), nullable=False),
    sa.Column('route_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('step_directions',
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('directions', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('direction_id')
    )
    op.create_table('steps',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('start_point', sa.Integer(), nullable=False),
    sa.Column('end_point', sa.Integer(), nullable=False),
    sa.Column('directions', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('u_routes',
    sa.Column('ur_id', sa.Integer(), nullable=False),
    sa.Column('u_routes', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('ur_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('user_routes', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('terms_agreement', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('waypoints',
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('waypoint_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waypoints')
    op.drop_table('users')
    op.drop_table('u_routes')
    op.drop_table('steps')
    op.drop_table('step_directions')
    op.drop_table('routes')
    op.drop_table('paths')
    op.drop_table('path_steps')
    op.drop_table('interest_points')
    op.drop_table('directions')
    op.drop_table('c_routes')
    # ### end Alembic commands ###
